/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculatorwithtest;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    public App calculator = new App();

    @Test
    public void testAdicao() {
        assertEquals(5, calculator.somar(2, 3));
    }

    @Test
    public void testSubtracao() {
        assertEquals(3, calculator.subtrair(6, 3));
    }

    @Test
    public void testMultiplicacao() {
        assertEquals(12, calculator.multiplicar(3, 4));
    }

    @Test
    public void testDivisao() {
        assertEquals(2.5, calculator.dividir(5, 2));
    }

    @Test
    public void testDivisaoPorZero() {
        assertThrows(IllegalArgumentException.class, () -> calculator.dividir(10, 0));
    }
    
    @Test
    public void testDivisaoErro() {
        assertEquals(3.0, calculator.dividir(10, 3));
    }
    
    @Test
    public void testSubtracaoErro() {
        assertEquals(8, calculator.subtrair(10, 3));
    }
}
